export enum EventPropertyDataType {
    String = 0,
    Guid = 1,
    Boolean = 2,
    Integer = 3,
    Decimal = 4,
    Date = 5,
    Time = 6,
    DateTime = 7,
    NullableGuid = 8,
    NullableBoolean = 9,
    NullableInteger = 10,
    NullableDecimal = 11,
    NullableDate = 12,
    NullableTime = 13,
    NullableDateTime = 14,
    ListBoolean = 15,
    ListDate = 16,
    ListDateTime = 17,
    ListDecimal = 18,
    ListGuid = 19,
    ListInteger = 20,
    ListString = 21,
    ListTime = 22,
    ObjectDictionary = 23,
}